### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by ORelio** [KoalaBR/spotlight#2]
Currently, the app GUI is mostly in German.
It would be nice if the app was available in English.
Here is a quick translation map using Google Translate:

````
German                  English
--------------------------------------------

Format                  Format
Hochformat              Vertical format
Querformat              Landscape format
beide                   Both

Titel anzeigen          Show title
Keinen Titel anzeigen   Do not show a title
Zeige titel             Show title

Anzeige                 Display
Flach                   Flat
In Ordnern nach Tags    In folders by tags

Suchen                  Search
Bild                    Image
Zurück                  Back

Daten geladen           Data Loaded
Ermittle URLs           Determine URLs
````
Of course it may contain translation errors.

**Comment by KoalaBR** [comment]
Thank you very much for your translation. The not yet pushed current version already has german and english translations. But it never hurts to cross check my translations with yours.

I hope to push the current version within the next two weeks. It should have an updated readme.md too.

Thanks for your feedback
Koala

**Comment by ORelio** [comment]
Actually I'm not 100% sure myself of all the translations but glad it could help even a little.
Feel free to close the issue when the English version will be pushed to the repository 🙂

**Comment by KoalaBR** [comment]
Just pushed my current version and made it Version 1.0. It contains the english translation (used on program start if you are not using the german locale). I added a release zip for Windows too.

Not yet done:
Didn't cross check your suggestions and created the zip archive manually.

Let me know if the program now works for you
Koala

**Comment by KoalaBR** [comment]
I just noticed that I forgot to add the .qm files to the release archive. I will update the archive tomorrow accordingly. 

Sorry about that.
KoalaBR

**Comment by ORelio** [comment]
Hi, sorry for the delay.

On Windows 7, out of the box, `MSVCP140.DLL` is missing, this can be solved by installing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-US/download/details.aspx?id=48145). Then the application launches.

At first, I had the same behavior than previously described in #3 but I noticed the dropdown menu for "Title" had nothing selected, after selecting "Don't show title" or "Show title", then images start downloading :+1:

Some feedback :

 * There is no direct access to the downloaded images folder. In my case, found it in `C:\Users\USERNAME\Pictures\download`
 * Once images are downloaded, the window becomes so big it doesn't fit in my screen and I can't access the Search and Image buttons anymore

Apart from that, it works! :sunglasses:

**Comment by KoalaBR** [comment]
Hi,

thank you for your feedback. I already have some changes lined up, but I didn't find the time to test them for both Linux and Windows and so haven't pushed them yet.

Regarding your problems:

- Window to large for desktop
  Sorry, I never considered that the images may be larger than the desktop size available. I changed the code to prevent the program window from getting larger than the primary desktop size. However, now the background image may not fully fit into the window.

- No option available to access the download folder.
  Good idea, never thought of that. Will implement this too.

- Missing dll for Windows.
  Yes, I only included Qt dlls and the program file. However I should at least say which redistributable you will need. 

- Wrong initial value for title combobox
  Will fix that.

The next version which includes all that should be available before the end of month.

Thanks for your feedback
Koala BR

**Comment by KoalaBR** [comment]
I updated the project to add the features you suggested. I rewrote the build instructions too, as the build should create a deploy on both Linux and Windows. This directory should contain all files need to run Spotlight. 

On Windows you may need to add OpenSSL DLLs, if they are not system wide installed.

**Comment by ORelio** [comment]
Seems like the app is now properly translated :slightly_smiling_face:
