### ISSUE TITLE
Download broken?

### ISSUE THREAD

**Issue by ORelio** [KoalaBR/spotlight#3]
The usage seems pretty straightforward but I cannot use it properly.
When clicking the `Suchen` button, the only message I get is the following:

![suchen](https://user-images.githubusercontent.com/1128206/35768552-cf17f07e-08fd-11e8-9466-25fb40392c57.png)

````
Done
Daten geladen - Ermittle URLs
````

No image seems to download.
Either I'm not doing it right, or the download feature seems broken.
Thanks for any help you can provide 🙂 

**Update:** OK, actually there *is* a "How to use" section in [Readme.md](https://github.com/KoalaBR/spotlight/blob/gh_remote/readme.md), and the images are not downloading.

**Comment by KoalaBR** [comment]
If your program directory contains only the files your screenshot shows, there are missing some. 

1) Your program directory should contain:
libeay32.dll
ssleay32.dll

These files are from openssl 1.0.1 and you can find a download list here:
https://wiki.openssl.org/index.php/Binaries

2) Additional subdirectories:
 - platforms
 - sqldrivers
 - imageformats

I copied those from my Qt installation dir, e.g. 

`C:\Qt\5.9.4\msvc2017_64\plugins\sqldrivers`

The current version just expects that everything is setup correctly which is unfortunate. I am currently updating the version with error output.

Thanks for your feedback and let me know if this works for you

Koala

**Comment by ORelio** [comment]
Hi,

Thanks for the additional details.

Unfortunately, that does not help for me, tried with both `openssl-1.0.1u-i386-win32.zip` and `openssl-1.0.1u-x64_86-win64.zip` from the [library release server](https://indy.fulgan.com/SSL/). Launching with the following set of files gives the same result:

````
imageformats/qgif.dll
imageformats/qgif.pdb
imageformats/qgifd.dll
imageformats/qgifd.pdb
imageformats/qicns.dll
imageformats/qicns.pdb
imageformats/qicnsd.dll
imageformats/qicnsd.pdb
imageformats/qico.dll
imageformats/qico.pdb
imageformats/qicod.dll
imageformats/qicod.pdb
imageformats/qjpeg.dll
imageformats/qjpeg.pdb
imageformats/qjpegd.dll
imageformats/qjpegd.pdb
imageformats/qsvg.dll
imageformats/qsvg.pdb
imageformats/qsvgd.dll
imageformats/qsvgd.pdb
imageformats/qtga.dll
imageformats/qtga.pdb
imageformats/qtgad.dll
imageformats/qtgad.pdb
imageformats/qtiff.dll
imageformats/qtiff.pdb
imageformats/qtiffd.dll
imageformats/qtiffd.pdb
imageformats/qwbmp.dll
imageformats/qwbmp.pdb
imageformats/qwbmpd.dll
imageformats/qwbmpd.pdb
imageformats/qwebp.dll
imageformats/qwebp.pdb
imageformats/qwebpd.dll
imageformats/qwebpd.pdb
libeay32.dll
platforms/qdirect2d.dll
platforms/qdirect2d.pdb
platforms/qdirect2dd.dll
platforms/qdirect2dd.pdb
platforms/qminimal.dll
platforms/qminimal.pdb
platforms/qminimald.dll
platforms/qminimald.pdb
platforms/qoffscreen.dll
platforms/qoffscreen.pdb
platforms/qoffscreend.dll
platforms/qoffscreend.pdb
platforms/qwindows.dll
platforms/qwindows.pdb
platforms/qwindowsd.dll
platforms/qwindowsd.pdb
Qt5Core.dll
Qt5Gui.dll
Qt5Network.dll
Qt5Sql.dll
Qt5Widgets.dll
Spotlight.exe
sqldrivers/qsqlite.dll
sqldrivers/qsqlite.pdb
sqldrivers/qsqlited.dll
sqldrivers/qsqlited.pdb
sqldrivers/qsqlmysql.dll
sqldrivers/qsqlmysql.pdb
sqldrivers/qsqlmysqld.dll
sqldrivers/qsqlmysqld.pdb
sqldrivers/qsqlodbc.dll
sqldrivers/qsqlodbc.pdb
sqldrivers/qsqlodbcd.dll
sqldrivers/qsqlodbcd.pdb
sqldrivers/qsqlpsql.dll
sqldrivers/qsqlpsql.pdb
sqldrivers/qsqlpsqld.dll
sqldrivers/qsqlpsqld.pdb
ssleay32.dll
````
````
Done
Daten geladen - Ermittle URLs
````
I ended up writing a script to download images using the URL from [spotlightprovider.cpp](https://github.com/KoalaBR/spotlight/blob/gh_remote/spotlightprovider.cpp#L17), thanks for it as I did not find the URL elsewhere before spotting your repository.

Of course when you'll be able to provide a pre-built release I can still test it. Meanwhile, I'll close this issue as it seems related to me not building the app properly as per #1 😉
